#!/usr/bin/ash
showfb(){
    dd if=/background.fb of=/dev/fb0 >/dev/null 2>&1
}
run_earlyhook(){
    lzop -d /background.fb.lzo -f 
    showfb
}

run_latehook(){
    showfb
}

run_cleanuphook(){
     rm -f /background.fb >/dev/null 2>&1
}

